name: Terraform CI/CD

on:
  push:
    branches:
      - "*"  # Runs on any branch push
  pull_request:
    types: [closed]  # Triggers when a PR is closed (merged)

jobs:
  terraform:
    name: Terraform Plan or Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./vpc
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        working-directory: ./vpc
        run: terraform plan -out=plan.tfplan

      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        working-directory: ./vpc
        run: terraform apply -auto-approve
